# Generated by Django 2.2.1 on 2019-06-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='materialmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mate_id', models.CharField(max_length=20)),
                ('mate_name', models.CharField(max_length=20)),
                ('mate_code', models.CharField(max_length=20)),
                ('mate_type', models.CharField(max_length=20)),
                ('mate_desc', models.CharField(max_length=20)),
                ('mate_updated_on', models.DateTimeField(auto_now_add=True)),
                ('mate_updated_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_material_master',
            },
        ),
        migrations.CreateModel(
            name='materialunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_unit_id', models.CharField(max_length=20)),
                ('mat_unit_type', models.CharField(max_length=20)),
                ('mat_unit_updated_on', models.DateTimeField(auto_now_add=True)),
                ('mat_unit_updated_by', models.CharField(max_length=20)),
                ('mate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='app.materialmaster')),
            ],
            options={
                'db_table': 'tbl_material_unit',
            },
        ),
        migrations.DeleteModel(
            name='TblConstSpec',
        ),
        migrations.DeleteModel(
            name='TblConstSpecMate',
        ),
        migrations.DeleteModel(
            name='TblMarterialMaster',
        ),
        migrations.DeleteModel(
            name='TblMaterialUnit',
        ),
    ]
