# Generated by Django 2.2.1 on 2019-06-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190618_1653'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materialmaster',
            table=None,
        ),
        migrations.AlterModelTable(
            name='materialunit',
            table=None,
        ),
    ]
