# Generated by Django 2.2.1 on 2019-06-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190618_1659'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materialmaster',
            table='tbl_material_master',
        ),
        migrations.AlterModelTable(
            name='materialunit',
            table='tbl_material_unit',
        ),
    ]
