# Generated by Django 2.2.1 on 2019-06-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAddress',
            fields=[
                ('add_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('com_id', models.CharField(max_length=32)),
                ('add_type', models.CharField(blank=True, max_length=20, null=True)),
                ('add_address_line1', models.CharField(blank=True, max_length=40, null=True)),
                ('add_addres_line2', models.CharField(blank=True, max_length=40, null=True)),
                ('add_city', models.CharField(blank=True, max_length=20, null=True)),
                ('add_state', models.CharField(blank=True, max_length=20, null=True)),
                ('add_country', models.CharField(blank=True, max_length=20, null=True)),
                ('add_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('add_updated_on', models.DateTimeField(blank=True, null=True)),
                ('add_updated_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCommChannel',
            fields=[
                ('com_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('cutomer_id', models.CharField(max_length=32)),
                ('com_type', models.CharField(max_length=30)),
                ('com_updated_on', models.DateTimeField(blank=True, null=True)),
                ('com_updated_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_comm_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCustomer',
            fields=[
                ('customer_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_code', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_tag', models.CharField(max_length=30)),
                ('customer_updated_on', models.DateTimeField(blank=True, null=True)),
                ('customer_updated_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCustomerAditionalAttribute',
            fields=[
                ('addinfo_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=32)),
                ('addinfo_attr', models.CharField(max_length=20)),
                ('addinfo_value', models.CharField(max_length=20)),
                ('addinfo_updated_on', models.DateTimeField(blank=True, null=True)),
                ('addinfo_updated_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_customer_aditional_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEmail',
            fields=[
                ('eml_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('com_id', models.CharField(max_length=32)),
                ('eml_address', models.CharField(max_length=40)),
                ('eml_updated_on', models.DateTimeField(blank=True, null=True)),
                ('eml_updated_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLegalInfo',
            fields=[
                ('legalinfo_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=32)),
                ('legalinfo_type', models.CharField(max_length=30)),
                ('legalinfo_value', models.CharField(blank=True, max_length=100, null=True)),
                ('legalinfo_updated_on', models.DateTimeField(blank=True, null=True)),
                ('legalinfo_updated_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_legal_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPhone',
            fields=[
                ('ph_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('com_id', models.CharField(max_length=32)),
                ('ph_isd_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ph_std_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ph_no', models.CharField(max_length=15)),
                ('ph_updated_on', models.DateTimeField(blank=True, null=True)),
                ('ph_updated_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProject',
            fields=[
                ('project_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=32)),
                ('project_name', models.CharField(max_length=30)),
                ('project_code', models.CharField(max_length=30)),
                ('project_type', models.CharField(max_length=30)),
                ('project_updated_on', models.DateTimeField(blank=True, null=True)),
                ('project_updated_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProjectAttributes',
            fields=[
                ('proj_att_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=32)),
                ('proj_attribute', models.CharField(blank=True, max_length=30, null=True)),
                ('proj_value', models.CharField(blank=True, max_length=30, null=True)),
                ('proj_att_updated_on', models.DateTimeField(blank=True, null=True)),
                ('proj_att_updated_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_project_attributes',
                'managed': False,
            },
        ),
    ]
